# -*- coding: utf-8 -*-
"""Challenge1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IZima1IuDJ8GZ34OdJ1A404DiZB42EE
"""

def fact_rec(n):
  if n==0 or n==1:
    return 1
  else:
    return n*fact_rec(n-1)
number=4
res=fact_rec(number)
print("The factorial of {} is {}".format(number,res))



